apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  clusterIP:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https
      port: 8443
      targetPort: 8443
    - name: backend
      port: 8201
      targetPort: 8201
  selector:
    app: vault
