apiVersion: v1 
kind: Namespace 
metadata: 
  name: k8s-vault
--- 
apiVersion: operators.coreos.com/v1 
kind: OperatorGroup 
metadata: 
  name: operatorgroup 
  namespace: k8s-vault 
spec: 
  targetNamespaces: 
  - k8s-vault 
---
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription
metadata:
  name: vault 
  namespace: k8s-vault 
spec:
  channel: beta 
  name: vault 
  source: operatorhubio-catalog
  sourceNamespace: olm