apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: webserver-deployment
  namespace: webapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      containers: 
      - name: apache 
        image: httpd
        ports: 
          - containerPort: 80
        volumeMounts: 
        - name: log 
          mountPath: /var/log/apache2 
      volumes:
      - name: log 
        emptyDir: {}