apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: webapp2
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: web
  selector:
    app: web